let authMode="login";
const state={role:"Student",page:"Dashboard",user:null,backendOnline:false,profile:null,recommendations:[],opportunities:[],applications:[],enrollments:[],portfolio:[],collaborations:[],analytics:null,notifications:[]};
const navs={Student:["Dashboard","Skill Assessment","Skill Profile","Recommendations","Live Market","Opportunities","Applications","Notifications","Learning","Portfolio","Collaboration Hub"],Academician:["Dashboard","Faculty Opportunities","Research","Training","Mentorship","Collaboration Hub"],Industry:["Dashboard","Post Opportunity","Candidates","Opportunities","Training Programs","Collaboration Hub"],Institution:["Dashboard","Skill Gap Analytics","Internships & Placements","Reports","Collaboration Hub"]};
const roleData={Student:"STUDENT PORTAL",Academician:"ACADEMICIAN PORTAL",Industry:"INDUSTRY PORTAL",Institution:"INSTITUTION PORTAL"};const $=id=>document.getElementById(id);
function toast(x){$("toast").textContent=x;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
function openLogin(){document.getElementById("landing").classList.add("hidden");document.getElementById("login").classList.remove("hidden");setAuthMode("login")}
function showLanding(){$("app").classList.add("hidden");$("login").classList.add("hidden");$("landing").classList.remove("hidden")}
function scrollToId(id){$(id)?.scrollIntoView({behavior:"smooth"})}
function setAuthMode(m){authMode=m;$("loginTab").classList.toggle("active",m==="login");$("registerTab").classList.toggle("active",m==="register");$("authNameWrap").style.display=m==="register"?"grid":"none";$("authRoleField").style.display=m==="register"?"grid":"none";$("authOrgField").style.display=m==="register"?"grid":"none";$("authSubmit").textContent=m==="register"?"Create SkillBridge account →":"Login to SkillBridge →"}
async function submitAuth(){const email=$("authEmail").value.trim(),password=$("authPassword").value;if(!email||!password)return toast("Enter email and password");try{if(authMode==="register"){const name=$("authName").value.trim();if(!name)return toast("Enter your name");await apiPost("/auth/register",{name,email,password,role:$("authRole").value,organization:$("authOrg").value.trim()});toast("Account created — now log in");$("authEmail").value=email;setAuthMode("login");return}const r=await apiPost("/auth/login",{email,password});localStorage.setItem("skillbridge_user",JSON.stringify(r.user));await enter(r.user)}catch(e){toast(e.message)}}
async function enter(user){state.user=user;state.role=user.role;state.page="Dashboard";$("landing").classList.add("hidden");$("login").classList.add("hidden");$("app").classList.remove("hidden");shell();state.opportunities=[];await loadBackendData();startNotificationStream();await render()}
function shell(){$("rolePill").textContent=state.role.toUpperCase();const n=state.user?.name||"User";$("userName").textContent=n;$("userRole").textContent=state.role;$("avatar").textContent=n[0].toUpperCase();$("sideNav").innerHTML=navs[state.role].map(x=>`<button class="${x===state.page?"active":""}" onclick="go('${x}')">${x}</button>`).join("")}
async function logout(){try{await apiPost("/auth/logout",{})}catch{}localStorage.removeItem("skillbridge_user");showLanding()}
async function boot(){setAuthMode("login");try{const u=await apiGet("/auth/me");localStorage.setItem("skillbridge_user",JSON.stringify(u));await enter(u)}catch{localStorage.removeItem("skillbridge_user")}}
let notificationSource=null;
function startNotificationStream(){
  if(notificationSource) notificationSource.close();
  if(!state.user) return;
  notificationSource=new EventSource(window.SKILLBRIDGE_API+"/notifications/stream", {withCredentials:true});
  notificationSource.addEventListener("notification",event=>{
    try{const n=JSON.parse(event.data);state.notifications.unshift(n);state.notifications=state.notifications.slice(0,50);toast(n.title+": "+n.message);if(state.page==="Notifications")render();}catch{}
  });
  notificationSource.onerror=()=>{if(notificationSource){notificationSource.close();notificationSource=null;}setTimeout(()=>{if(state.user)startNotificationStream()},10000)};
}
async function loadNotifications(){try{state.notifications=await apiGet("/notifications")}catch(e){state.notifications=[]}}
async function markNotification(id){try{await apiPatch("/notifications/"+id+"/read",{});await loadNotifications();render()}catch(e){toast(e.message)}}
async function markAllNotifications(){try{await apiPatch("/notifications/read-all",{});await loadNotifications();render()}catch(e){toast(e.message)}}
async function notifications(){await loadNotifications();return `<div class="section-title"><div><h2>Notifications</h2><p class="muted">Persistent activity with live updates.</p></div><button class="btn-sm primary" onclick="markAllNotifications()">Mark all read</button></div><div class="grid">${state.notifications.map(n=>`<div class="card ${n.is_read?"":"notification-unread"}"><span class="tag">${n.type}</span><h3>${n.title}</h3><p>${n.message}</p><span class="muted">${new Date(n.date).toLocaleString()}</span>${n.is_read?"":"<button class=\"btn-sm\" onclick=\"markNotification("+n.id+")\">Mark read</button>"}</div>`).join("")||empty("No notifications yet.")}</div>`}
async function loadBackendData(){try{state.opportunities=(await apiGet("/opportunities")).map(normalize);if(state.role==="Student"){const [r,a,p,l,port,c]=await Promise.all([apiGet("/recommendations"),apiGet("/applications/me"),apiGet("/skill-profiles/me"),apiGet("/learning/me"),apiGet("/portfolio"),apiGet("/collaborations?role_name=Student")]);state.recommendations=r.map(normalize);state.applications=a;state.profile=p;state.enrollments=l;state.portfolio=port;state.collaborations=c}if(state.role==="Institution")state.analytics=await apiGet("/analytics");state.backendOnline=true}catch(e){state.backendOnline=false;console.warn(e)}}
function normalize(o){return {...o,skills:Array.isArray(o.skills)?o.skills.join(" · "):String(o.skills||""),match:Number(o.match||0)}}
async function go(p){state.page=p;shell();await render()}
async function render(){ $("pageEyebrow").textContent=roleData[state.role];$("pageTitle").textContent=state.page;const fn=pages[state.page]||dashboard;$("content").innerHTML=await fn()}
function stat(t,v,s){return `<div class="card"><span class="muted">${t}</span><div class="metric">${v}</div><span class="muted">${s}</span></div>`}
function dashboard(){if(state.role==="Student")return studentDash();if(state.role==="Industry")return industryDash();if(state.role==="Institution")return institutionDash();return academicDash()}
function studentDash(){return `<div class="grid grid4">${stat("Profile",state.profile?"92%":"38%","Skill profile")}${stat("Best match",state.recommendations[0]?state.recommendations[0].match+"%":"—","AI ranking")}${stat("Applications",state.applications.length,"Tracked")}${stat("Learning",state.enrollments.length,"Enrolled")}</div><div class="section-title"><h2>Recommended for you</h2><button class="btn-sm" onclick="go('Recommendations')">View all</button></div><div class="grid">${state.recommendations.slice(0,3).map(opCard).join("")||empty("Complete your skill assessment to generate recommendations.")}</div>`}
function academicDash(){return `<div class="grid grid4">${stat("Faculty opportunities","12","Programs")}${stat("Collaborations","7","Active")}${stat("Mentorships","5","Active")}${stat("Research links","4","Connected")}</div><div class="section-title"><h2>Academia × Industry</h2></div><div class="grid">${["Faculty Opportunities","Research","Training","Mentorship"].map(x=>`<div class="card op-card"><span class="tag">Academician</span><h3>${x}</h3><p class="muted">Industry-aligned programs and collaboration.</p><button class="btn-sm primary" onclick="go('${x}')">Open →</button></div>`).join("")}</div>`}
function industryDash(){return `<div class="grid grid4">${stat("Open opportunities",state.opportunities.length,"Published")}${stat("Candidate engine","AI","Skill matching")}${stat("Applications","Live","Pipeline")}${stat("Programs","6","Training")}</div><div class="card"><h2>Talent pipeline</h2><p class="muted">Publish an opportunity and open Candidate Discovery to rank student profiles.</p></div>`}
function institutionDash(){const a=state.analytics;return `<div class="grid grid4">${stat("Students",a?.students??"—","Registered")}${stat("Profiles",a?.profiles??"—","Coverage "+(a?.profile_completion??0)+"%")}${stat("Applications",a?.applications??"—","Tracked")}${stat("Selected",a?.selected??"—","Outcomes")}</div><div class="cards2"><div class="card"><h3>Student skill supply</h3><p class="muted">${(a?.top_student_skills||[]).map(x=>x[0]+" ("+x[1]+")").join(" · ")||"No data"}</p></div><div class="card"><h3>Industry demand</h3><p class="muted">${(a?.industry_demand||[]).map(x=>x[0]+" ("+x[1]+")").join(" · ")||"No data"}</p></div></div>`}
function opCard(o){return `<div class="card op-card"><span class="tag">${o.type}</span><h3>${o.title}</h3><p class="muted">${o.provider} · ${o.location}</p><div class="row">${o.skills.split(" · ").map(x=>`<span class="tag">${x}</span>`).join("")}</div><div class="footer"><span class="match">${o.match?o.match+"% match":"Open"}</span><button class="btn-sm primary" onclick="apply(${o.id||0})">View / Apply</button></div></div>`}
async function apply(id){if(!id)return toast("This is a live opportunity only when the backend is connected");try{await apiPost("/applications",{opportunity_id:id});toast("Application submitted");await loadBackendData();go("Applications")}catch(e){toast(e.message)}}
function assessment(){return `<div class="card form"><span class="eyebrow">SKILL ASSESSMENT</span><h2>Build your skill profile</h2><p class="muted">Tell SkillBridge where you are today.</p><div class="field"><label>Technical skill level</label><select id="tech"><option value="55">Beginner</option><option value="75">Intermediate</option><option value="92">Advanced</option></select></div><div class="field"><label>Soft skill level</label><select id="soft"><option value="55">Beginner</option><option value="75">Intermediate</option><option value="90">Advanced</option></select></div><div class="field"><label>Skills</label><input id="skills" placeholder="Python, Pandas, NumPy, Machine Learning"></div><div class="field"><label>Strengths</label><input id="strengths" placeholder="Python, Problem Solving"></div><div class="field"><label>Skill gaps</label><input id="gaps" placeholder="Machine Learning, SQL"></div><div class="field"><label>Career interests</label><input id="interests" placeholder="AI/ML, Data Science"></div><button class="primary" onclick="saveAssessment()">Complete Assessment →</button></div>`}
async function saveAssessment(){const csv=id=>$(id).value.split(",").map(x=>x.trim()).filter(Boolean);try{await apiPut("/skill-profiles",{technical_score:+$("tech").value,soft_score:+$("soft").value,skills:csv("skills"),strengths:csv("strengths"),gaps:csv("gaps"),interests:csv("interests")});toast("Skill profile saved");await loadBackendData();go("Skill Profile")}catch(e){toast(e.message)}}
function profile(){const p=state.profile||{technical_score:0,soft_score:0,skills:[],strengths:[],gaps:[],interests:[]};return `<div class="grid grid4">${stat("Technical",Math.round(p.technical_score)+"%","Assessment")}${stat("Soft skills",Math.round(p.soft_score)+"%","Assessment")}${stat("Skills",p.skills.length,"Tracked")}${stat("Gaps",p.gaps.length,"Growth areas")}</div><div class="cards2"><div class="card"><h3>Strengths</h3><p class="muted">${p.strengths.join(" · ")||"Complete assessment"}</p></div><div class="card"><h3>Skill gaps</h3><p class="muted">${p.gaps.join(" · ")||"None identified"}</p></div></div><div class="card"><h3>Career interests</h3><p class="muted">${p.interests.join(" · ")||"Not set"}</p></div>`}
function recommendations(){return `<div class="section-title"><h2>AI recommendations</h2><span class="muted">${state.backendOnline?"Live ranking":"Backend offline"}</span></div><div class="grid">${state.recommendations.map(opCard).join("")||empty("Complete your skill assessment first.")}</div>`}
async function opportunities(){let d;try{d=await apiGet("/opportunities?limit=50")}catch(e){return empty(e.message)}return `<div class="section-title"><div><h2>Opportunity marketplace</h2><p class="muted">${d.total||0} opportunities · search and filter live data</p></div></div><div class="filter-bar"><input id="marketQ" placeholder="Search role, company or skill"><select id="marketType"><option value="">All types</option><option>Internship</option><option>Project</option><option>Job</option><option>Apprenticeship</option></select><input id="marketSkills" placeholder="Skills: Python, SQL"><button class="btn-sm primary" onclick="filterMarketplace()">Filter</button></div><div id="marketResults" class="grid">${(d.items||[]).map(opCard).join("")||empty("No opportunities found.")}</div>`}
async function filterMarketplace(){const q=encodeURIComponent(document.getElementById("marketQ")?.value||"");const type=encodeURIComponent(document.getElementById("marketType")?.value||"");const skills=encodeURIComponent(document.getElementById("marketSkills")?.value||"");try{const d=await apiGet("/opportunities?q="+q+"&kind="+type+"&skills="+skills+"&limit=50");document.getElementById("marketResults").innerHTML=(d.items||[]).map(opCard).join("")||empty("No opportunities match those filters.")}catch(e){toast(e.message)}}
function applications(){return `<div class="card"><table class="table"><tr><th>Opportunity</th><th>Status</th><th>Applied</th></tr>${state.applications.map(a=>`<tr><td>${a.opportunity?.title||"Opportunity"}</td><td class="status">${a.status}</td><td>${a.created_at?new Date(a.created_at).toLocaleDateString():"—"}</td></tr>`).join("")||'<tr><td colspan="3">No applications yet.</td></tr>'}</table></div>`}
async function skillGap(){try{const d=await apiGet("/skill-gaps");return `<div class="section-title"><h2>Skill Gap Intelligence</h2><p class="muted">Market demand compared with your current profile.</p></div><div class="grid">${(d.priority_gaps||[]).map(x=>`<div class="card"><span class="tag">Demand ${x.market_demand}</span><h3>${x.skill}</h3><div class="progress"><i style="width:${x.priority}%"></i></div><p class="muted">Priority ${x.priority}% · Build this skill to unlock more opportunities.</p></div>`).join("")||empty("No priority gaps found.")}</div><div class="section-title"><h2>Recommended learning</h2></div><div class="grid">${(d.recommended_learning||[]).map(x=>`<div class="card"><h3>${x.title}</h3><p class="muted">${x.provider} · ${x.target_gaps.join(" · ")}</p><button class="btn-sm primary" onclick="enroll(${x.id})">Start learning →</button></div>`).join("")}</div>`}catch(e){return empty(e.message)}}
async function learning(){let items=[];try{items=await apiGet("/learning")}catch{}return `<div class="section-title"><h2>Learning Hub</h2></div><div class="grid">${items.map(x=>`<div class="card"><span class="tag">${x.kind}</span><h3>${x.title}</h3><p class="muted">${x.provider} · ${x.skills.join(" · ")}</p><button class="btn-sm primary" onclick="enroll(${x.id})">Enroll</button></div>`).join("")}</div><div class="section-title"><h2>My learning</h2></div><div class="grid">${state.enrollments.map(x=>`<div class="card"><b>${x.item?.title||"Program"}</b><div class="progress"><i style="width:${x.progress}%"></i></div><span class="muted">${x.progress}% · ${x.status}</span></div>`).join("")||empty("No enrollments yet.")}</div>`}
async function enroll(id){try{await apiPost("/learning/"+id+"/enroll",{});toast("Enrolled");await loadBackendData();go("Learning")}catch(e){toast(e.message)}}
async function portfolio(){return `<div class="section-title"><h2>Digital Portfolio</h2><button class="btn-sm primary" onclick="addPortfolio()">+ Add project</button></div><div class="grid">${state.portfolio.map(x=>`<div class="card"><span class="tag">${x.kind}</span><h3>${x.title}</h3><p class="muted">${x.description}</p><div class="row">${x.skills.map(s=>`<span class="tag">${s}</span>`).join("")}</div></div>`).join("")||empty("Showcase projects, internships, certifications and achievements.")}</div>`}
async function addPortfolio(){const title=prompt("Project / achievement title");if(!title)return;try{await apiPost("/portfolio",{title,kind:"Project",description:prompt("Short description")||"",skills:state.profile?.skills||[]});toast("Portfolio item added");await loadBackendData();go("Portfolio")}catch(e){toast(e.message)}}
async function collaboration(){let items=[];try{items=await apiGet("/collaborations?role_name="+encodeURIComponent(state.role))}catch{}return `<div class="section-title"><h2>Collaboration Hub</h2></div><div class="grid">${items.map(x=>`<div class="card"><span class="tag">${x.kind}</span><h3>${x.title}</h3><p class="muted">${x.provider}</p><p>${x.description}</p></div>`).join("")||empty("No collaboration items yet.")}</div>`}
function postOpportunity(){return `<div class="card form"><h2>Post an opportunity</h2><div class="field"><label>Title</label><input id="otitle" placeholder="AI/ML Internship"></div><div class="field"><label>Type</label><select id="otype"><option>Internship</option><option>Project</option><option>Apprenticeship</option><option>Job</option><option>Training</option></select></div><div class="field"><label>Required skills</label><input id="oskills" placeholder="Python, SQL, Machine Learning"></div><div class="field"><label>Location</label><input id="oloc" value="Flexible"></div><div class="field"><label>Description</label><textarea id="odesc"></textarea></div><button class="primary" onclick="createOpportunity()">Publish Opportunity</button></div>`}
async function createOpportunity(){try{await apiPost("/opportunities",{title:$("otitle").value,type:$("otype").value,provider:state.user.organization||state.user.name,location:$("oloc").value,skills:$("oskills").value.split(",").map(x=>x.trim()).filter(Boolean),description:$("odesc").value});toast("Opportunity published");await loadBackendData();go("Opportunities")}catch(e){toast(e.message)}}
async function candidates(){const mine=state.opportunities.filter(x=>x.provider===(state.user.organization||state.user.name));const o=mine[0]||state.opportunities[0];if(!o)return empty("Publish an opportunity first.");try{const rows=await apiGet("/candidates/"+o.id);return `<div class="section-title"><h2>Candidate discovery</h2><span class="muted">${o.title}</span></div><div class="card"><table class="table"><tr><th>Candidate</th><th>Match</th><th>Coverage</th><th>Matched</th><th>Gaps</th></tr>${rows.map(x=>`<tr><td>${x.student}</td><td class="match">${x.match}%</td><td>${x.skill_coverage}%</td><td>${x.matched_skills.join(" · ")||"—"}</td><td>${x.missing_skills.join(" · ")||"None"}</td></tr>`).join("")}</table></div>`}catch(e){return empty(e.message)}}
function faculty(){return `<div class="grid">${["Industry Internships","FDP & Training","Research Collaboration","Mentorship"].map(x=>`<div class="card"><span class="tag">Academician</span><h3>${x}</h3><p class="muted">Industry-aligned programs for faculty and researchers.</p></div>`).join("")}</div>`}
async function analytics(){const a=state.analytics||await apiGet("/analytics");return `<div class="grid grid4">${stat("Students",a.students,"Registered")}${stat("Profiles",a.profiles,a.profile_completion+"% coverage")}${stat("Applications",a.applications,"Tracked")}${stat("Selected",a.selected,"Outcomes")}</div><div class="cards2"><div class="card"><h3>Skill supply</h3><p class="muted">${a.top_student_skills.map(x=>x[0]+" — "+x[1]).join(" · ")}</p></div><div class="card"><h3>Industry demand</h3><p class="muted">${a.industry_demand.map(x=>x[0]+" — "+x[1]).join(" · ")}</p></div></div>`}
function placements(){return `<div class="card"><h2>Internships & Placements</h2><p class="muted">Track participation and outcomes through institution analytics.</p><button class="primary" onclick="go('Reports')">View reports →</button></div>`}
async function reports(){const r=await apiGet("/institution/reports");return `<div class="card"><h2>Institution report</h2><p class="muted">Generated ${new Date(r.generated_at).toLocaleString()}</p><pre>${JSON.stringify(r.metrics,null,2)}</pre></div>`}
function empty(x){return `<div class="empty"><h2>SkillBridge</h2><p>${x}</p></div>`}
const pages={"Notifications":notifications,"Live Market":()=>window.renderLiveMarket?window.renderLiveMarket():empty("Loading market data…"),"Skill Assessment":assessment,"Skill Profile":profile,Recommendations:recommendations,Opportunities:opportunities,Applications:applications,Learning:learning,Portfolio:portfolio,"Collaboration Hub":collaboration,"Post Opportunity":postOpportunity,Candidates:candidates,"Faculty Opportunities":faculty,Research:collaboration,Training:collaboration,Mentorship:collaboration,"Training Programs":collaboration,"Skill Gap Analytics":skillGap,"Internships & Placements":placements,Reports:reports};
setInterval(()=>{if(state.user&&state.page==="Live Market"&&window.renderLiveMarket)render()},300000);window.addEventListener("DOMContentLoaded",boot);